workflows:
  my-workflow:
    name: My workflow name
    instance_type: mac_mini
    max_build_duration: 60
    scripts:
      - brew install php
      - brew install phoronix-test-suite
      - phoronix-test-suite benchmark smallpt
    publishing:
      email:
        recipients:
          - rimante@nevercode.io